# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'OmniChat' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OmniChat

  target 'OmniChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OmniChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod ‘Firebase’
  pod ‘Firebase/Database’
  pod ‘Firebase/Auth’
  pod 'TwilioVideo', '~> 1.2.0’
  pod ‘AudioKit’
end
